#!/usr/bin/env bash
#Usage
#./curbm filename N_visible N_hidden k_samples batchsize epochs lr mom sparsity
./curbm ../../data/L_32_T_2-45_binary.dat 1024 256 6 100 10 0.1 0.8 0.00005
#./curbm ../../data/L_64-SG-beta_5-bits_256-N_s_1000.bin 4096 16 25 50 50 0.1 0.7 0.0001
